name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - master  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false  # 禁用子模块检查

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v22.16.0'

      - name: Install Dependencies
        run: npm install

      - name: Install Hexo Git Deployer
        run: |
          npm install hexo-deployer-git --save
          npm install hexo-cli -g

      - name: Clean and Generate Static Files
        run: |
          hexo clean
          hexo generate

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Configure Hexo Deploy
        # 临时修改 _config.yml 的部署配置（避免本地配置暴露密钥）
        run: |
          echo '
          deploy:
            type: git
            repo: https://${{ secrets.SECRET_HEXO }}@github.com/essaimhello/blog.git
            branch: gh-pages  # 推荐用 gh-pages 分支专门存放 Pages 静态文件
            message: "Deploy from GitHub Actions: {{ now('YYYY-MM-DD_HH-mm-ss') }}"
          ' >> _config.yml

      - name: Deploy to GitHub Pages
        run: hexo deploy  # 执行 hexo d 完成部署